name: Install NPM Dependencies

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: cd npm
        run: cd npm

      - name: Generate package-lock.json
        run: npm i --package-lock-only