name: Install NPM Dependencies

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate package-lock.json
        run: |
          cd npm
          npm i --package-lock-only --ignore-scripts