name: publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            os-name: linux
          - os: windows-latest
            os-name: win64
          - os: macos-latest
            os-name: macos

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: |
          cargo build --all --release
          mkdir builds
          mkdir builds/svelte-cli-${{ matrix.os-name }}

      - name: Move compiled binary to builds folder (Windows)
        if: ${{ matrix.os-name == 'win64' }}
        run: mv target/release/svelte-cli.exe builds/svelte-cli-${{ matrix.os-name }}

      - name: Move compiled binary to builds folder (non-Windows)
        if: ${{ matrix.os-name != 'win64' }}
        run: mv target/release/svelte-cli builds/svelte-cli-${{ matrix.os-name }}

      - name: Create binary archive
        run: tar -C builds -czvf builds/svelte-cli-${{ matrix.os-name }}.tar.gz svelte-cli-${{ matrix.os-name }}

      - name: Get Current Version
        uses: dante-signal31/rust-app-version@v1.0.0
        id: crate-version

      - name: Upload release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          tag_name: ${{ steps.crate-version.outputs.app_version }}
          files: |
            builds/svelte-cli-${{ matrix.os-name }}.tar.gz

  npm_publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    defaults:
      run:
        working-directory: ./npm
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup .npmrc file to publish to npm
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: npm i
        run: npm i --ignore-scripts

      - name: Publish package to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

  cargo_publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Publish crate to cargo
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_ACCESS_TOKEN }}
          
