name: publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc-mingw-w64-x86-64
          rustup target add x86_64-pc-windows-gnu
          rustup target add x86_64-unknown-linux-gnu
          rustup target add x86_64-apple-darwin
          
          mkdir dist
          mkdir builds

      - name: Build
        run: |
          cargo build --all-targets --release
          mkdir builds/svelte-cli-win64
          mkdir builds/svelte-cli-linux
          mkdir builds/svelte-cli-macos
          cp target/x86_64-pc-windows-gnu/release/svelte-cli.exe builds/svelte-cli-win64
          cp target/x86_64-unknown-linux-gnu/release/svelte-cli.exe builds/svelte-cli-linux
          cp target/x86_64-apple-darwin/release/svelte-cli.exe builds/svelte-cli-macos
          
      - name: Create binary archives
        run: |
          tar -C builds -czvf dist/svelte-cli-win64.tar.gz svelte-cli-win64
          tar -C builds -czvf dist/svelte-cli-linux.tar.gz svelte-cli-linux
          tar -C builds -czvf dist/svelte-cli-macos.tar.gz svelte-cli-macos
      
      - name: Get Current Version
        uses: dante-signal31/rust-app-version@v1.0.0
        id: crate-version
      
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ steps.crate-version.outputs.app_version }}
          files: |
            dist/svelte-cli-win64.tar.gz
            dist/svelte-cli-win32.tar.gz
            dist/svelte-cli-linux.tar.gz
            dist/svelte-cli-macos.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PUBLISH_TOKEN }}

#      - name: Publish npm package
#        env:
#          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
#        run: |
#          echo "//registry.npmjs.org/:_authToken=$NPM_ACCESS_TOKEN" > ".npmrc"
#          npm publish
#
#      - name: Publish cargo package
#        env:
#          CARGO_ACCESS_TOKEN: ${{ secrets.CARGO_ACCESS_TOKEN }}
#        run: |
#          cargo login "$CARGO_ACCESS_TOKEN"
#          cargo publish
